import type { PetAnimalType } from "@/lib/supabase/types";

export interface BreedGuideSeed {
  breed_name: string;
  breed_name_en: string;
  animal_type: PetAnimalType;
  size_category: string;
  lifespan: string;
  personality: string;
  health_notes: string;
  exercise_level: string;
  grooming_level: string;
  beginner_friendly: boolean;
  saju_tendency: string;
  seo_slug: string;
  summary: string;
  body: string;
  tags: string[];
}

/** Excel 품종별 가이드 시트 기준 30건 (견종·묘종·기타) */
export const BREED_GUIDE_SEEDS: BreedGuideSeed[] = [
  { breed_name: "말티즈", breed_name_en: "Maltese", animal_type: "dog", size_category: "small", lifespan: "12–15년", personality: "애착이 깊고 예민한 편.", health_notes: "눈물·슬개골·치아 관리.", exercise_level: "low", grooming_level: "high", beginner_friendly: true, saju_tendency: "수(水) — 차분한 휴식", seo_slug: "maltese", summary: "소형견 대표. 실내 생활에 적합.", body: "짧은 산책·눈 주변·치아 루틴을 꾸준히.", tags: ["소형견", "초보"] },
  { breed_name: "푸들", breed_name_en: "Poodle", animal_type: "dog", size_category: "small", lifespan: "12–15년", personality: "똑똑하고 활동적.", health_notes: "귀·피부 알레르기 점검.", exercise_level: "medium", grooming_level: "high", beginner_friendly: true, saju_tendency: "목(木) — 탐색·놀이", seo_slug: "poodle", summary: "지능형 견종. 정신 자극이 필수.", body: "노즈워크·퍼즐 장난감을 병행하세요.", tags: ["소형견", "훈련"] },
  { breed_name: "포메라니안", breed_name_en: "Pomeranian", animal_type: "dog", size_category: "small", lifespan: "12–16년", personality: "호기심 많고 경계심 있음.", health_notes: "슬개골·호흡기·치아.", exercise_level: "low", grooming_level: "high", beginner_friendly: true, saju_tendency: "화(火) — 짧은 놀이", seo_slug: "pomeranian", summary: "작은 체구지만 에너지 풍부.", body: "과도한 점프는 관절에 부담.", tags: ["소형견"] },
  { breed_name: "치와와", breed_name_en: "Chihuahua", animal_type: "dog", size_category: "small", lifespan: "14–18년", personality: "대담하고 주인에게 집중.", health_notes: "저체온·치아·슬개골.", exercise_level: "low", grooming_level: "low", beginner_friendly: true, saju_tendency: "화(火) — 따뜻한 보온", seo_slug: "chihuahua", summary: "초소형. 추위에 약함.", body: "겨울 외출 시 보온 필수.", tags: ["소형견"] },
  { breed_name: "요크셔 테리어", breed_name_en: "Yorkshire Terrier", animal_type: "dog", size_category: "small", lifespan: "13–16년", personality: "당당하고 활발.", health_notes: "치아·기관지·털 관리.", exercise_level: "low", grooming_level: "high", beginner_friendly: false, saju_tendency: "금(金) — 정돈·루틴", seo_slug: "yorkshire-terrier", summary: "장모 소형견.", body: "매일 빗질과 치아 케어.", tags: ["소형견", "그루밍"] },
  { breed_name: "비숑 프리제", breed_name_en: "Bichon Frise", animal_type: "dog", size_category: "small", lifespan: "12–15년", personality: "밝고 사교적.", health_notes: "피부·눈·귀 염증.", exercise_level: "medium", grooming_level: "high", beginner_friendly: true, saju_tendency: "토(土) — 규칙적 루틴", seo_slug: "bichon-frise", summary: "알레르기 비교적 적은 편.", body: "정기 미용과 귀 청소.", tags: ["소형견", "초보"] },
  { breed_name: "시츄", breed_name_en: "Shih Tzu", animal_type: "dog", size_category: "small", lifespan: "10–16년", personality: "온순하고 가족 친화.", health_notes: "눈·호흡·척추.", exercise_level: "low", grooming_level: "high", beginner_friendly: true, saju_tendency: "토(土) — 안정", seo_slug: "shih-tzu", summary: "실내견에 적합.", body: "짧은 산책과 눈 주변 관리.", tags: ["소형견"] },
  { breed_name: "닥스훈트", breed_name_en: "Dachshund", animal_type: "dog", size_category: "small", lifespan: "12–16년", personality: "호기심·사냥 본능.", health_notes: "디스크(허리) 보호.", exercise_level: "medium", grooming_level: "low", beginner_friendly: false, saju_tendency: "토(土) — 바닥 생활", seo_slug: "dachshund", summary: "계단·점프 제한 중요.", body: "소파 오르내림 최소화.", tags: ["소형견", "허리"] },
  { breed_name: "프렌치 불독", breed_name_en: "French Bulldog", animal_type: "dog", size_category: "small", lifespan: "10–12년", personality: "차분하고 애교 많음.", health_notes: "호흡·더위·피부 주름.", exercise_level: "low", grooming_level: "low", beginner_friendly: true, saju_tendency: "토(土) — 서늘한 휴식", seo_slug: "french-bulldog", summary: "브라키세팔릭 주의.", body: "여름 산책은 이른 아침·저녁.", tags: ["소형견", "단두"] },
  { breed_name: "웰시 코기", breed_name_en: "Welsh Corgi", animal_type: "dog", size_category: "medium", lifespan: "12–15년", personality: "영리하고 활동적.", health_notes: "허리·비만.", exercise_level: "medium", grooming_level: "medium", beginner_friendly: true, saju_tendency: "목(木) — 지능 놀이", seo_slug: "welsh-corgi", summary: "목양견 출신.", body: "체중 관리와 허리 보호.", tags: ["중형견"] },
  { breed_name: "시바 이누", breed_name_en: "Shiba Inu", animal_type: "dog", size_category: "medium", lifespan: "12–15년", personality: "독립적·깔끔함.", health_notes: "알레르기·탈모 시즌.", exercise_level: "medium", grooming_level: "medium", beginner_friendly: false, saju_tendency: "금(金) — 자립 공간", seo_slug: "shiba-inu", summary: "고집 있을 수 있어 훈련 일관성 필요.", body: "긍정 강화 훈련 추천.", tags: ["중형견", "훈련"] },
  { breed_name: "비글", breed_name_en: "Beagle", animal_type: "dog", size_category: "medium", lifespan: "12–15년", personality: "친화적·냄새 추적.", health_notes: "비만·귀 감염.", exercise_level: "high", grooming_level: "low", beginner_friendly: true, saju_tendency: "목(木) — 노즈워크", seo_slug: "beagle", summary: "식탐·도망 주의.", body: "리드줄 필수, 간식량 조절.", tags: ["중형견"] },
  { breed_name: "보더 콜리", breed_name_en: "Border Collie", animal_type: "dog", size_category: "medium", lifespan: "12–15년", personality: "매우 영리·일하기 좋아함.", health_notes: "관절·눈 질환.", exercise_level: "high", grooming_level: "medium", beginner_friendly: false, saju_tendency: "목(木) — 업무·훈련", seo_slug: "border-collie", summary: "운동·두뇌 자극 부족 시 문제행동.", body: "아질리티·트릭 훈련 병행.", tags: ["중형견", "운동"] },
  { breed_name: "시베리안 허스키", breed_name_en: "Siberian Husky", animal_type: "dog", size_category: "large", lifespan: "12–14년", personality: "활발·무리 본능.", health_notes: "더위·탈모·눈.", exercise_level: "high", grooming_level: "high", beginner_friendly: false, saju_tendency: "수(水)·목(木) — 장거리 활동", seo_slug: "siberian-husky", summary: "더운 날씨에 취약.", body: "충분한 운동과 그늘.", tags: ["대형견"] },
  { breed_name: "골든 리트리버", breed_name_en: "Golden Retriever", animal_type: "dog", size_category: "large", lifespan: "10–12년", personality: "온순·가족견.", health_notes: "관절·암·비만.", exercise_level: "high", grooming_level: "medium", beginner_friendly: true, saju_tendency: "토(土) — 가족 교감", seo_slug: "golden-retriever", summary: "초보에게 인기.", body: "매일 산책·수영도 좋음.", tags: ["대형견", "초보"] },
  { breed_name: "래브라도 리트리버", breed_name_en: "Labrador Retriever", animal_type: "dog", size_category: "large", lifespan: "10–12년", personality: "친근·식욕 왕성.", health_notes: "비만·관절·귀.", exercise_level: "high", grooming_level: "low", beginner_friendly: true, saju_tendency: "수(水) — 수영·놀이", seo_slug: "labrador-retriever", summary: "가장 흔한 가족견.", body: "사료량·간식 엄격 관리.", tags: ["대형견", "초보"] },
  { breed_name: "저먼 셰퍼드", breed_name_en: "German Shepherd", animal_type: "dog", size_category: "large", lifespan: "9–13년", personality: "충성·경계·학습 빠름.", health_notes: "엉덩이·소화.", exercise_level: "high", grooming_level: "medium", beginner_friendly: false, saju_tendency: "금(金) — 임무·훈련", seo_slug: "german-shepherd", summary: "사회화·훈련 필수.", body: "초기 사회화에 시간 투자.", tags: ["대형견", "훈련"] },
  { breed_name: "믹스견(소형)", breed_name_en: "Small Mixed Breed", animal_type: "dog", size_category: "small", lifespan: "12–16년", personality: "개체마다 다양.", health_notes: "유기견은 건강검진 먼저.", exercise_level: "medium", grooming_level: "medium", beginner_friendly: true, saju_tendency: "개별 성향 확인", seo_slug: "mixed-dog-small", summary: "품종보다 개별 성향 중시.", body: "입양 후 2–4주 루틴 관찰.", tags: ["믹스견", "입양"] },
  { breed_name: "믹스견(중대형)", breed_name_en: "Medium-Large Mixed Breed", animal_type: "dog", size_category: "large", lifespan: "10–14년", personality: "다양.", health_notes: "관절·체중.", exercise_level: "medium", grooming_level: "medium", beginner_friendly: true, saju_tendency: "개별 성향 확인", seo_slug: "mixed-dog-large", summary: "크기에 맞는 운동량.", body: "산책·놀이 강도를 체형에 맞게.", tags: ["믹스견"] },
  { breed_name: "코리안 숏헤어", breed_name_en: "Korean Shorthair", animal_type: "cat", size_category: "medium", lifespan: "15–20년", personality: "독립·적응력 좋음.", health_notes: "비만·방광염.", exercise_level: "low", grooming_level: "low", beginner_friendly: true, saju_tendency: "토(土) — 안정", seo_slug: "korean-shorthair", summary: "우리나라 대표 묘종.", body: "습식·캣타워·창가 자리.", tags: ["단모", "초보"] },
  { breed_name: "페르시안", breed_name_en: "Persian", animal_type: "cat", size_category: "medium", lifespan: "12–17년", personality: "차분·조용.", health_notes: "털뭉침·눈물·호흡.", exercise_level: "low", grooming_level: "high", beginner_friendly: false, saju_tendency: "금(金) — 청결", seo_slug: "persian", summary: "장모 관리 부담 큼.", body: "매일 빗질.", tags: ["장모"] },
  { breed_name: "브리티시 숏헤어", breed_name_en: "British Shorthair", animal_type: "cat", size_category: "medium", lifespan: "12–17년", personality: "느긋·독립.", health_notes: "비만·심장.", exercise_level: "low", grooming_level: "low", beginner_friendly: true, saju_tendency: "토(土) — 규칙", seo_slug: "british-shorthair", summary: "둥근 체형.", body: "급식량 조절.", tags: ["단모", "초보"] },
  { breed_name: "스코티시 폴드", breed_name_en: "Scottish Fold", animal_type: "cat", size_category: "medium", lifespan: "11–14년", personality: "온순·앉기 좋아함.", health_notes: "연골·관절 이슈.", exercise_level: "low", grooming_level: "medium", beginner_friendly: false, saju_tendency: "토(土) — 낮은 가구", seo_slug: "scottish-fold", summary: "관절 건강 모니터링.", body: "높이 점프 줄이기.", tags: ["단모"] },
  { breed_name: "러시안 블루", breed_name_en: "Russian Blue", animal_type: "cat", size_category: "medium", lifespan: "15–20년", personality: "수줍·가족에게 애정.", health_notes: "비만·스트레스.", exercise_level: "low", grooming_level: "low", beginner_friendly: true, saju_tendency: "수(水) — 조용한 공간", seo_slug: "russian-blue", summary: "낯선 이에게 경계.", body: "은신처·천천히 적응.", tags: ["단모"] },
  { breed_name: "메인쿤", breed_name_en: "Maine Coon", animal_type: "cat", size_category: "large", lifespan: "12–15년", personality: "온화·대형.", health_notes: "심장·관절.", exercise_level: "medium", grooming_level: "high", beginner_friendly: true, saju_tendency: "목(木) — 높이·탐색", seo_slug: "maine-coon", summary: "대형묘.", body: "넓은 화장실·캣타워.", tags: ["장모", "대형묘"] },
  { breed_name: "랙돌", breed_name_en: "Ragdoll", animal_type: "cat", size_category: "large", lifespan: "12–17년", personality: "안기 좋아함·온순.", health_notes: "비만·방광.", exercise_level: "low", grooming_level: "medium", beginner_friendly: true, saju_tendency: "수(水) — 부드러운 환경", seo_slug: "ragdoll", summary: "안아 들 때 몸 맡김.", body: "무리한 안기는 피하기.", tags: ["장모"] },
  { breed_name: "벵갈", breed_name_en: "Bengal", animal_type: "cat", size_category: "medium", lifespan: "12–16년", personality: "활동적·호기심.", health_notes: "에너지 발산.", exercise_level: "high", grooming_level: "low", beginner_friendly: false, saju_tendency: "화(火) — 사냥 놀이", seo_slug: "bengal", summary: "야생형 외모.", body: "캣휠·인터랙티브 장난감.", tags: ["활동적"] },
  { breed_name: "샴", breed_name_en: "Siamese", animal_type: "cat", size_category: "medium", lifespan: "15–20년", personality: "수다·애착.", health_notes: "치아·호흡·비만.", exercise_level: "medium", grooming_level: "low", beginner_friendly: true, saju_tendency: "화(火) — 교감", seo_slug: "siamese", summary: "외로움에 민감.", body: "함께 시간·놀이.", tags: ["단모", "교감"] },
  { breed_name: "믹스묘", breed_name_en: "Mixed Breed Cat", animal_type: "cat", size_category: "medium", lifespan: "15–18년", personality: "개체마다 다양.", health_notes: "정기 검진.", exercise_level: "medium", grooming_level: "medium", beginner_friendly: true, saju_tendency: "개별 성향", seo_slug: "mixed-cat", summary: "품종보다 개성.", body: "입양 후 환경 적응 관찰.", tags: ["믹스", "입양"] },
  { breed_name: "토끼", breed_name_en: "Rabbit", animal_type: "other", size_category: "small", lifespan: "8–12년", personality: "조용·스트레스 예민.", health_notes: "소화·이갈·발톱.", exercise_level: "medium", grooming_level: "low", beginner_friendly: false, saju_tendency: "토(土) — 넓은 케이지", seo_slug: "rabbit", summary: "건초·넓은 공간 필수.", body: "잡아 들기보다 바닥 교감.", tags: ["소동물", "초보주의"] },
  { breed_name: "햄스터", breed_name_en: "Hamster", animal_type: "other", size_category: "small", lifespan: "2–3년", personality: "야행·단독 사육.", health_notes: "습도·탈출·치아.", exercise_level: "medium", grooming_level: "low", beginner_friendly: true, saju_tendency: "수(水) — 은신·휠", seo_slug: "hamster", summary: "짝지어 키우면 싸움.", body: "밤 활동·쳇바퀴 제공.", tags: ["소동물"] },
];
